apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: kops.k8s.local
  name: master-1c
spec:
  cloudLabels:
    Project: PROJECT_NAME
  image: ami-0f65ac71a3f129066
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-1c
  role: Master
  rootVolumeSize: 50
  subnets:
  - ap-southeast-1c
