apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: kops.k8s.local
  name: nodes
spec:
  cloudLabels:
    Project: PROJECT_NAME
  image: ami-0f65ac71a3f129066
  machineType: c5.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 128
  subnets:
  - ap-southeast-1a
  - ap-southeast-1b
  - ap-southeast-1c
