apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: kops.k8s.local
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    Project: PROJECT_NAME
  cloudProvider: aws
  configBase: s3://terraform-state
  etcdClusters:
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-1c
      name: c
    name: main
  - etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-1c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.0
  masterInternalName: api.internal.kops.k8s.local
  masterPublicName: api.kops.k8s.local
  networkCIDR: 10.0.0.0/16
  networkID: vpc-0000 #VPC_ID
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 172.16.0.0/12
  sshAccess:
  - 10.0.0.0/16
  subnets:
  - cidr: 10.0.10.0/24
    egress: nat-000 #NAT_ID
    id: subnet-000 #WORKER_SUBNET_ID_ZONE1A
    name: ap-southeast-1a
    type: Private
    zone: ap-southeast-1a
  - cidr: 10.0.20.0/24
    egress: nat-000 #NAT_ID
    id: subnet-000 #WORKER_SUBNET_ID_ZONE1B
    name: ap-southeast-1b
    type: Private
    zone: ap-southeast-1b
  - cidr: 10.0.30.0/24
    egress: nat-000 #NAT_ID
    id: subnet-000 #WORKER_SUBNET_ID_ZONE1C
    name: ap-southeast-1c
    type: Private
    zone: ap-southeast-1c
  - cidr: 10.0.1.0/24
    id: subnet-000 #MASTER_SUBNET_ID_ZONE1A
    name: utility-ap-southeast-1a
    type: Utility
    zone: ap-southeast-1a
  - cidr: 10.0.2.0/24
    id: subnet-000 #MASTER_SUBNET_ID_ZONE1B
    name: utility-ap-southeast-1b
    type: Utility
    zone: ap-southeast-1b
  - cidr: 10.0.3.0/24
    id: subnet-000 #MASTER_SUBNET_ID_ZONE1C
    name: utility-ap-southeast-1c
    type: Utility
    zone: ap-southeast-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
